### ISSUE TITLE
Should we set the minimum length of vectors to the `gsdd_cf()` function to 54 to guard against trying to pass weekly values? 

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/teckfish#22]
@aylapear and @sarahLy9 - what do you think?

**Comment by sarahLy9** [comment]
Thats not a bad idea but I would lean towards making it very explicit in the documentation that this is for daily temperatures. It is possible someone using the function could pull in data from just one or two months depending on what they are looking into?

**Comment by joethorley** [comment]
If they do two months or more they will be fine (28 + 30 = 58). It doesn't seem a good idea to be trying to do this calculation with less than two months of data so I think we are fine. 

I've modified the opening paragraph to say

>  It is the accumulated thermal units (in C) during the growing season based on the mean daily water temperature values.

**Comment by sarahLy9** [comment]
makes sense to me!

**Comment by joethorley** [comment]
I've gone with a minimum of 90 days

**Comment by sarahLy9** [comment]
My only thought is if a user wants to compare months and tries to pass data grouped by month one at a time. 

 My only other idea is to add a mandatory argument of time_steps = "day" to force the user to acknowledge that it is only functional for daily values. If we ever expand functionality to interpolate or create daily averages we could add options to that argument.

**Comment by joethorley** [comment]
Good thoughts - i'm thinking of adding a higher level function that takes a time series of data and aggregates daily etc.
